disconf-redis:
    image: redis:3.2.11
disconf-mysql:
    image: mysql:5.7
    
    volumes:
        - ${pwd}/mysql/mysql.cnf:/etc/mysql/my.cnf
        - ${pwd}/mysql/sql:/docker-entrypoint-initdb.d
        - ${pwd}/mysql/mysqlData:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=123456
    ports:
        - "3306:3306"
disconf-zoo:
    image: zookeeper:3.4.12
    ports:
        - "2181:2181"
disconf-web:
    image: tomcat:8-jre8
    links:
        - disconf-redis
        - disconf-mysql
        - disconf-zoo
    volumes:
        - ${pwd}/disconf-rd/working/war:/usr/local/tomcat/webapps/ROOT
        - ${pwd}/disconf-rd/tomcatlogs:/usr/local/tomcat/logs
disconf-nginx:
    image: nginx:1.9
    links:
        - disconf-web
    volumes:
        - ${pwd}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ${pwd}/disconf-rd/working/war/html:/home/work/dsp/disconf-rd/war/html:ro
        - ${pwd}/nginx/nginxlogs:/home/work/var/logs/disconf
    ports:
        - "8081:8081"